### ISSUE TITLE
Issue with ignoring padding for specific edges

### ISSUE THREAD

**Issue by ivancucer** [DWilliames/paddy-sketch-plugin#1]
Hey @DWilliames 👋

Thank you very much for this really handy plugin ❤️
But I noticed an issue with ignoring padding for specific edges 🐞
Please take a look at this screencast: https://monosnap.com/file/yxe5a1aA2zkYMHFykytMJr0m7gzLdh 🔍
Source file: https://monosnap.com/file/2DEcKoYR2aChmra8C2xsHshV7BBQOf 💎

macOS 10.12.6 (16G1212)
Sketch 48.2 (47327)
Paddy 1.0

Thanks in advance!

Best!
Ivan

**Comment by DWilliames** [comment]
Thanks for the detailed bug report @ivancucer! 👍 
I'll look into this as soon as I can. :)

**Comment by DWilliames** [comment]
So, I've figured out how to make sure that the padding does ignore the edges for the symbol instance.

However, because you've got an AutoLayout 'Stack Group'; it's not aware that it is a stack group. So it looks like this — it thinks it will be shorter, because it doesn't realise that they'll be 'stacked'.
![image](https://user-images.githubusercontent.com/6570446/35802887-efd827f6-0ac5-11e8-914a-69c49f6998bf.png)

How important is it for you that will take into account Stack Groups? :P 
I think I can figure out how to do it; it will just be a bit fiddly.

**Comment by DWilliames** [comment]
I managed to figure out how to make it account for Stack Groups.
I'll close this issue for now. I just pushed an update with the fix — please check it works. If it doesn't, then re-open this issue 👍
