### ISSUE TITLE
[Enhancement] Layers/groups that contain [] as part of their name don’t get Paddy'd

### ISSUE THREAD

**Issue by frankko** [DWilliames/paddy-sketch-plugin#20]
"layername[0] [8 4]" or "groupname[1] [8v]" won’t get matched.

Maybe your RegExp should be changed from 

`/\[(.*)\]/g` (match anything between the first `[` and last `]`, which grabs `0] [8 4` and `1] [8v` in my examples, respectively)

to something like

`/\[([^]]+)\]$/g` (match only characters between the `[` and `]` at the end of the string, which would get `8 4` and `8v` in my examples).

**Comment by DWilliames** [comment]
@frankko Thanks for this. Thanks for even proposing a solution too!!

This was something I overlooked.
Unfortunately, due to 'cocoascript' (the language the plugin is technically written in), being a pain. Your proposed Regex doesn't compile — even though it should work, and would work in Javascript.

Instead, I think `/.*\[(.*)\]/g` should work as expected. It also means that `[xxx]` doesn't have to be the last thing in the string. It will just grab the last occurrence in the string.

**Comment by DWilliames** [comment]
@frankko I have just released **version 1.0.3** that should make this work. I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍
