### ISSUE TITLE
[Bug] Misalignment on centered text (for symbols)

### ISSUE THREAD

**Issue by sldx** [DWilliames/paddy-sketch-plugin#21]
I created a simple button made of a rounded rectangle and a longish text. Then made that a symbol. 

When I override the text, below a certain length the text is not properly centered. If I don't make it a symbol it works fine

![image](https://user-images.githubusercontent.com/1038751/36163224-674d5384-10f1-11e8-8d2d-758d90a9a79c.png)

**Comment by DWilliames** [comment]
Thanks for reaching out @sldx.

I'm able to re-create this. The trick is to set the resizing to 'left and right' on the text layer. I'd say this is a bug; because Paddy should probably do this for you, if you have centered text.

<img width="225" alt="screen shot 2018-02-15 at 8 50 50 am" src="https://user-images.githubusercontent.com/6570446/36230061-57f1773e-122d-11e8-82e8-8f97c9b30965.png">

![2018-02-15 08 52 11](https://user-images.githubusercontent.com/6570446/36230166-994f267c-122d-11e8-8a5e-16a1b974c08f.gif)

Let me know if that fixes it for you?

**Comment by sldx** [comment]
Yup, that works, cheers!

But agree it should be done automatically.

**Comment by DWilliames** [comment]
@sldx  I have just released **version 1.0.3** that will automatically set the resizing of centered text to 'left' + 'right' as detailed above. I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍

**Comment by sldx** [comment]
You da man!
