### ISSUE TITLE
Issue on group positioning

### ISSUE THREAD

**Issue by MrBiscuit** [DWilliames/paddy-sketch-plugin#5]
Various sized layer group's Y position was nudged -6px on every 'automatic spacing update' when using the 'middle' expression. 

btw, it would be very handy if there is a way to fix the group's position, that way we don't have to manually put it back where it was when rearranging its sub-layers 😄

You are doing an incredibly good job at making a lean and to the point plugin, I have my Anima auto layout uninstalled the first minute I put my hands on this one, Anima is getting way puffier than it should and losing its primary focus. Big thumb up for paddy👍🏻 keep up the good work mate!

macOS 10.13.2 (17C88)
Sketch 48.2 (47327)

**Comment by DWilliames** [comment]
Thanks heaps for the feedback @MrBiscuit, really appreciate it!!

I've commented about this issue in #8, which is a duplicate.
I've found a solution.

I will also change it so that the groups position is 'pinned' to the top-left. So hopefully you don't have to keep manually putting it back where it was :P Let me know if that helps.

**Comment by DWilliames** [comment]
This should now be fixed. Please verify in the latest version. 
If it's not fixed, then please re-open this issue 👍
