### ISSUE TITLE
[Enhancement] Don't ignore text layers prefixed with '-' where the layer name is the text value

### ISSUE THREAD

**Issue by tikshow** [DWilliames/paddy-sketch-plugin#66]
Whenever I like to use a negative value in a text for example -25% and then try to add a padding to it, the padding jumps away because of the Ignoring specific layers mode. Of course it can be solved by simply removing the minus from the layer name.

**Comment by DWilliames** [comment]
Thanks for this @tikshow!

That's a really good point. I hadn't considered something like this. What do you think would be a good solution for this?

Perhaps layers need to be prefixed with a space after the dash? e.g. '- ' instead of '-'
Although, you'd still have the case of people writing text values that may begin with '- ' 🤔 

This might be a tricky one to solve without breaking what other people already have set up too.

**Comment by jackiecorn** [comment]
I'd propose the solution to be auto renaming any existing text layers starting with a - in the name to have a * prefix so it will be *-25% in your case, which will not be ignored by paddy.

**Comment by DWilliames** [comment]
This should now be fixed v1.0.7 – if you find it still doesn't work; then please re-open this issue.
