### ISSUE TITLE
[BUG] Automatic update doesn't work

### ISSUE THREAD

**Issue by jacobnielsen88** [DWilliames/paddy-sketch-plugin#83]
**Expected behavior:**
The paddings of a group should automatically change/update, when I update the values in the layer name. 

**Actual behavior:**
Nothing happens. The padding remains the same. 

I'm running Sketch 49.1 and Paddy 1.0.6
I tried restarting Sketch, and tried uinstalling paddy. But nothing seems to be working.

**Comment by chloesil** [comment]
I'm having this issue as well, within the same Sketch 49.1 and Paddy 1.0.6

But my issue is ONLY within a Sketch file I inherited from another designer that was (most likely) created in an earlier version of Sketch. I am assuming this is the problem but not 100% sure.

**Comment by jacobnielsen88** [comment]
Unfortunately, mine doesn't work in new Sketch files either :(

**Comment by DWilliames** [comment]
Thanks all. I can't seem to reproduce this at the moment. It seems to be working for me.
@jacobnielsen88 can you try selecting from the Menu bar `Plugins > Paddy > Enable / disable automatic updating` and see if a message appears saying 'Paddy automation: enabled'.

Otherwise, can you please provide a screen recording or something to show the broken behaviour?

Cheers,
Dave

**Comment by jacobnielsen88** [comment]
I updated to 1.07 and everything is working again! 

Thanks for an amazing plugin, by the way.

**Comment by Robwearsglasses** [comment]
Hello! I am having the same issue. I am currently using Sketch 49.1 and Paddy 1.0.7, and nothing is dynamically resizing. I have also used a test file (mention in a youtube tutorial), with no results. Here is a video of Paddy not functioning.

https://gyazo.com/edcccd6f817721a8e4c2d35222a0f104

**Comment by Ida-Marika** [comment]
Hi,
Just want to give some input to this.

I experienced the same issue with the automatic update of the padding, when editing directly in the layer name. It did not work for the group, but if I created a symbol and edited the padding in the layer on the Symbols page, it worked as expected.
ABOVE EXPERIENCE, WAS WHEN RUNNING: Sketch version 50 and Paddy version 1.0.7

Then I updated Sketch to version 50.2 (still the same version of Paddy), and the issue was gone when working in a new document. However, the issue remains in the old document created in Sketch version 50.

Just want to add - Paddy is an awesome plugin!! Well done :)
